### ISSUE TITLE
[David](ETL_project)

### ISSUE THREAD

**Issue by DavidNPastrana** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#10]
https://github.com/DavidNPastrana/ETL_project_happiness

**Comment by OrianAmpuero** [comment]
Muy bien David! El repo organizado y readme bien explicado con visualización para entender mejor los datos. En cuanto al código, bien comentado y limpio, el ERD a mi parecer es mejor mostrarlo en una captura ya que es más fácil de ver la carga que descargar el archivo y abrirlo en Workbench. En general buen proyecto!
