### ISSUE TITLE
[Lola] (ETL-Project)

### ISSUE THREAD

**Issue by delbrioariasl** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#11]
https://github.com/delbrioariasl/W4_ETL_Project/tree/main

**Comment by OrianAmpuero** [comment]
Muy bien Lola!! El repo y el readme correctos, desde el desarrollo del proyecto y la muestra de carga de datos. En cuanto al código me parece buen inicio de escrapeo para un proyecto final, hay más que sacar pero se que lo puedes hacer con tiempo. En general me parece que todo esta bien.
