### ISSUE TITLE
[Jaime](project_ETL )

### ISSUE THREAD

**Issue by RCJaime** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#12]
https://github.com/Jaimercmail/ETL-completa

**Comment by OrianAmpuero** [comment]
Buen trabajo Jaime! El repo esta organizado pero sería mejor tener no solo la carpeta de jupyter notebooks si no la de 'data', 'SQL'... por fuera para diferenciar cada cosa; el readme resumido pero esta bien y en cuanto al código bien en general, yo solo agregaría el ERD de SQL para ver las relaciones de las tablas.
