### ISSUE TITLE
[NICO GCD]web_scrapin_w4_1

### ISSUE THREAD

**Issue by NGCOS46** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#13]

**Comment by NGCOS46** [comment]
https://github.com/NGCOS46/web_scrapin_w4_1/tree/main

**Comment by OrianAmpuero** [comment]
Buen trabajo Nico! El repo organizado y el readme bien explicado. En cuanto al código limpio y en general muy bien, yo agregaría el ERD de SQL, por otra parte hay unos archivos .py que no tienen contenido así que mejor eliminarlos ñporque no se ven bien y de resto es buen inicio de escrapeo.
