### ISSUE TITLE
[Rodrigo](ETL Project)

### ISSUE THREAD

**Issue by rodrigogtz99** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#14]
https://github.com/rodrigogtz99/tourism_database_ETL.git

**Comment by OrianAmpuero** [comment]
Bien Rodrigo, en cuanto al repo le falta organización y el readme esta mejorable, en mi opinión al ser un proyecto de ETL mostraría más el proceso de extracción de datos o de carga a SQL y solo mostraría un par de gráficos que ayuda a contar la historia y entender los datos.
Sobre el código bien pero cuidado de no tener varios notebooks con la misma información o usados como borradores porque no se ve bien y es un poco lioso. El archivo de SQL donde solo escribiste esa querie básica, mejor no colocarlo porque no se ve bien y mejor coloca la imagen del ERD.
Por lo demás vas bien, sigue esforzándote y aprovechando a  tope.
