### ISSUE TITLE
[Borja Dorado](w4-project_ETL)

### ISSUE THREAD

**Issue by BorjaDorado** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#2]
https://github.com/BorjaDorado/Chess

**Comment by OrianAmpuero** [comment]
Buen trabajo Borja! 
En cuanto al readme falta info en algunos puntos, así que mejor lo arreglas o quitas por ejemplo (visualización o conclusión ya que no aparece nada), recuerda el orden de carpetas en el repo.
Bien escrapeo y comentado el código; aunque me falta ver la carga del csv en sql como comentaste en el readme.
