### ISSUE TITLE
[borja.dolagaray]_[w4-project_ETL]

### ISSUE THREAD

**Issue by borjadola** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#3]
https://github.com/borjadola/Proyecto_ETC_Precipitaciones.git

**Comment by OrianAmpuero** [comment]
Excelente trabajo Borja! El repo y el readme muy bien estructurados y ordenado, buen abrebocas del proyecto. En cuanto al código, bien comentado y limpio que se entiende cada paso realizado, las funciones en su sitio. Solo me faltaría ver el ERD de SQL para tener la carga de base de datos a la vista y listo. Como bonus la visualización que ayuda a entender los datos y en resumen me parece muy buen trabajo.
