### ISSUE TITLE
[Nico.V](Project_ETL)

### ISSUE THREAD

**Issue by nicovilla23** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#4]
https://github.com/nicovilla23/Project_ETL

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Nico! El repo organizado y el readme correcto con la explicación de los pasos hasta mostrar la carga de los mismos. En cuanto al código me parece que todo está muy bien escrapeado y relacionado, mostrando la visualización para entender mejor los datos. Como algún punto de mejora, podrías poner las cookies en gitignore para que no se vea directamente.
En general excelente!
