### ISSUE TITLE
[Carlos González](w4-project_ETL)

### ISSUE THREAD

**Issue by chiinwy** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#5]
https://github.com/chiinwy/Proyecto_ETL

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Carlos, el repo y el readme están correctos en cuanto a organización y redacción del mismo ya que haz mostrado todo el proceso adicionando como bonus la visualización de los datos que es importante para entender mejor lo que hay. El código está limpio y bien el escrapeo, además de mostrar la carga de datos en SQL, en general me parece todo muy bien.
