### ISSUE TITLE
[Esteban] w4-project_ETL

### ISSUE THREAD

**Issue by esteban-bit** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#6]
https://github.com/esteban-bit/Project-ETL.git

**Comment by OrianAmpuero** [comment]
Bien Esteban! El repo organizado a falta del notebook principal que sería bueno que lo agregaras a una carpeta, el readme está bien explicado, con SQL y visualización que ayuda a ver los datos. El código está bien, me parece buen inicio de escrapeo y que puedes ir puliendo si lo usas para tu proyecto final.
