### ISSUE TITLE
[MartaRG] (w4-project_ETL)

### ISSUE THREAD

**Issue by MartaRggc** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#7]
https://github.com/MartaRggc/Shkrappy.git

**Comment by OrianAmpuero** [comment]
Excelente trabajo Marta!! Desde el repo bien organizado y el readme explicado a detalle, todo el proceso y además con visualización para entender más los datos. En cuanto al código, todo limpio y bien usado el escrapeo hasta la carga en mongo, las funciones en su sitio y en general solo decirte que da gusto ver un proyecto así y sé que seguirás mejorando y perfeccionando hasta el proyecto final.
