### ISSUE TITLE
[IbaiGallego](w4-project_ETL)

### ISSUE THREAD

**Issue by IbaiGallego** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#8]
https://github.com/IbaiGallego/etl_anime_scrapping.git

**Comment by OrianAmpuero** [comment]
Muy bien Ibai! El repo organizado y el readme bien explicado, me hubiese hecho falta mostrar algo de mongo para ver la carga de datos ahí. En cuanto al código limpio y correcto, en general buen trabajo.
