### ISSUE TITLE
[DemianFigueiredo](w4-project_ETL)

### ISSUE THREAD

**Issue by DemianFigueiredo** [Ironhack-Data-Madrid-Julio-2023/w4-project_ETL#9]
https://github.com/DemianFigueiredo/s_elt_project.git

**Comment by OrianAmpuero** [comment]
Bien Demian! El repo organizado y el readme explicando el proceso; en cuanto al código está correcto, a mi parecer falta el ERD de SQL para ver como quedan las tablas y es más visual, pero de resto esta todo bien.
